//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/GolfControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GolfControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GolfControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GolfControls"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""ee61ffe7-ab30-467a-96d4-a48eb106b151"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8c8b978e-d840-4fc0-9842-3059c771e69d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""11140f85-9a71-48ca-9f18-0f75e6f540b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""c6b9cca9-47f2-404e-9739-f63004371df2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fad2d37a-56d3-4e53-820b-284699430096"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""445bb61f-9870-4fa5-a2df-6c7d981bef88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2654b474-dcf9-44d5-8217-cbdb094b0d5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""123ae985-4568-4278-88cc-41389f4620de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""aaccb0c9-7ecd-431f-a31a-9065961cf6a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b374162c-501a-4c56-a58b-4df8c005b7a0"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""150b5775-41c8-40f1-bf19-050705b31eef"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""6db46392-3114-4a12-9fba-4fb922cc1b7b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c8a479c4-6d23-4f4a-9ea1-8d277aa11be2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2c1d43d3-8d02-4100-b164-2dd4bd55cd20"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cd563299-0055-4b0f-8161-ac5df3ac0fc2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""88525a48-8174-4a3a-9472-baacedf8177d"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""15e85f7a-4145-4646-97bd-bff096b96417"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6c45642f-a39a-4c1e-bdb4-3abac01b9aaf"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fff634b5-31cf-4212-bf42-ecd1dc4c6dff"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""899faba1-d425-4457-910f-66b8e09962ec"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""be3cb9b6-9b0b-47b5-9dc3-e6880ba88d5f"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""6b973b53-0d97-4f6f-b8cd-9a58d0c9e569"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7d5ce385-7eb7-4c72-b86b-1c5299aba4f0"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0b6d7cc9-a475-4278-a6fd-6c59d35945cd"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""baffdd96-e433-4609-af8b-e1b672fedde2"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1ec8c8e3-8498-4d8a-9e78-032ae2529b68"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""e91f4944-fb77-40d5-90c0-73dd8bec65a7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5d89778f-a284-4eaf-8a33-991e8b674346"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cc86c4a0-8c26-4ac2-9e13-9558905d8111"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ce1052b9-c286-4a7a-96be-c951071b6883"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f55baf7d-f0e9-4c9b-abf5-c9a098445c4c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3300fc8b-7920-47ad-baa3-a2ae11747b75"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0dd871a7-f609-486a-99ea-4a511dd2b2d8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b6025282-e5da-46fd-a228-86a13c18e690"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""543b90e5-94ee-4110-95d1-e8e8f363b190"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3b6a4757-802b-4df6-bf2a-1e0836c09a01"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a01440ec-6562-4f9c-87d6-97698bfc64df"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96a1f216-a4e1-482a-8ad1-97a8126d2606"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ef193ad-fe9f-4e0c-80cb-b75d7575b0fa"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fccf01b-786a-49fd-805c-4a7f5e1238b0"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae9159e-3c56-49bb-b363-df9bd6531e6a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b579d7c-d656-44f3-b230-aca8dc723e84"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0617ab88-8ba0-4273-acb9-280124220b8e"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fba5724-3a2f-4c0b-a17b-c8062ebac493"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20654e62-b355-46ba-b402-b6501d539520"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5967f18e-cebb-4321-8776-3cb5c69c9cd1"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a063489-18dd-44c2-a86b-8f62f13fd381"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71d34fc2-4afd-451a-bd46-81dd2bfcdbad"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d11828f-b002-499f-b591-a709b80a38b0"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PromptPlayer"",
            ""id"": ""efad1241-20e9-4c83-8b94-406f4c5e67dd"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""714edd47-9909-4597-b4aa-6bb8f369cfcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""3149a549-e438-4a04-85a9-ff394a46b242"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89ce22a9-46c3-4d09-80cc-7faa3a22d8bd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88a6f2d6-4d9d-4e07-a944-db5cce12008a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11c8a41e-0763-4856-b388-331f483207b6"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d72dfd8e-d91c-42a7-b176-cff2d4452c6a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AimingActions"",
            ""id"": ""225906bc-62c6-404d-bf30-fc91184b5db6"",
            ""actions"": [
                {
                    ""name"": ""AimPosition"",
                    ""type"": ""Value"",
                    ""id"": ""53e840aa-331f-471c-a0c8-04b1619b6379"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpinPosition"",
                    ""type"": ""Value"",
                    ""id"": ""a9bdd341-a219-4b84-b1df-586debfa2f23"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetSpin"",
                    ""type"": ""Button"",
                    ""id"": ""f24c3112-3ffc-4450-9033-79cef9b80e40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeClub"",
                    ""type"": ""Button"",
                    ""id"": ""300ce802-fc7c-4dc7-a767-6615676631b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomOut"",
                    ""type"": ""Button"",
                    ""id"": ""1e1b7bb1-bbcb-40fe-be76-ba862305f15d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomOutAim"",
                    ""type"": ""Button"",
                    ""id"": ""239d3d78-b460-430f-8a19-b1d4c55986a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortPutt"",
                    ""type"": ""Button"",
                    ""id"": ""8a46b784-c8fd-465b-81c5-59cdb1c05c4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubmitAim"",
                    ""type"": ""Button"",
                    ""id"": ""ecc0453d-d154-4f4e-adbc-7e3fe88fb6e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""wasd"",
                    ""id"": ""91bf1e54-24a1-4663-b3e6-72e2d49df8e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""09a84266-e147-4175-b9db-3cc0bbc09bfd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""692bd803-2c59-4525-a29e-37db1151f594"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2c145be7-ef6a-438a-9ac4-c2421fa4a65f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2a1149d6-02fb-4365-babf-8a95b95256db"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""arrow_keys"",
                    ""id"": ""1b982595-ccf9-483c-9d81-3187f792263d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fce6133d-cb47-4984-a483-299ebf5775a9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f3efd829-25f3-41a8-83b2-fa95397c485f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2ad6fbc3-6eb6-4c3e-8b70-d97fcdbc754a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b9a4d40a-afc5-46dc-b2de-249ce7de848c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""dpad"",
                    ""id"": ""fb77dfbd-5d8b-421a-b3f3-ea4d550c9f5e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""20600d9f-ef36-4906-829c-e06d8a25efed"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e60a99f8-c268-446d-929a-6bd2f6e194ea"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cc8765da-ace9-4612-acbc-538f3e51ba5a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b9b80876-5bbb-4f0a-9775-9096648ee045"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""leftstick"",
                    ""id"": ""e50cea40-c797-4d4d-9b82-f4514cd14e4f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9f111f40-e8e5-4daa-bac7-672d97912fb9"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cfe41140-64b5-4969-9a61-f794c27081af"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0f023e01-c700-43c4-a81b-7745f8f162cc"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""78b549e0-19db-48db-a4ee-3689eb542820"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""25f26f6b-39a3-49af-b069-1fbf1bdd4f82"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeClub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97a5bce7-2297-4e41-9594-956496c9e974"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeClub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83a7b56f-ad69-4272-baeb-ba85caeb9a0d"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f525449-35d8-4120-b8b9-fa67529b70d7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d1eadc4-4ec1-482f-a62f-1c33e0565f7a"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomOutAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4ef076c-5fd4-46ab-9417-a86c580e6c5a"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortPutt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""966c1649-727a-4094-93e3-cb44b0acaa58"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortPutt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b97e0fcb-23bf-4420-b25f-894967383281"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05b73ad1-56b0-4796-81d9-73b84493ce61"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3552475-d0c6-458b-84f5-c949a85d5c4f"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetSpin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""rightstick"",
                    ""id"": ""8e79d2ef-e64a-430a-8eff-850ae066aa25"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinPosition"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0af046c1-197f-4927-8dd3-bdf6f1ab072e"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""010a3376-8edc-463f-9de9-620a327f043d"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6e8819ef-7e7d-48bf-b63d-badf87d8ee11"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cd9bf4e4-e69f-4bdc-99df-5fbf38e129b7"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""HittingActions"",
            ""id"": ""a90ee806-d603-4dc6-990e-81e694938006"",
            ""actions"": [
                {
                    ""name"": ""CancelHit"",
                    ""type"": ""Button"",
                    ""id"": ""d89c871b-7efc-4e08-b0d8-5aa6a1596dc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartHit"",
                    ""type"": ""Button"",
                    ""id"": ""583c6d2d-7f87-4c32-8e0d-18f1b6d8a487"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubmitHit"",
                    ""type"": ""Button"",
                    ""id"": ""0eb362c6-7719-4715-8929-6421fff43884"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""51ae7c65-7523-4ae5-9170-88fa429ce590"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85c92b74-6b6c-44a6-b5f2-00956adaeef1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""509016f8-2c9a-4d6b-adc4-6125c39456bf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bc7aaed-8bb5-4b8f-b3b7-dca05e39a426"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76b10306-31fb-45da-bd0b-3eac72dfe335"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c92352-4c70-491b-a610-8a4f13ad8394"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartHit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PowerUps"",
            ""id"": ""3af88005-70c2-4300-bad7-95b7934869d2"",
            ""actions"": [
                {
                    ""name"": ""UsePowerUp"",
                    ""type"": ""Button"",
                    ""id"": ""c97aa83c-ed2d-4524-a0bf-7b10bc3381bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa1cb5b5-79ce-40c6-99cb-c909d0cbd432"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""409f9389-9085-49fb-8248-582b6b295a8d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        // PromptPlayer
        m_PromptPlayer = asset.FindActionMap("PromptPlayer", throwIfNotFound: true);
        m_PromptPlayer_Continue = m_PromptPlayer.FindAction("Continue", throwIfNotFound: true);
        m_PromptPlayer_Skip = m_PromptPlayer.FindAction("Skip", throwIfNotFound: true);
        // AimingActions
        m_AimingActions = asset.FindActionMap("AimingActions", throwIfNotFound: true);
        m_AimingActions_AimPosition = m_AimingActions.FindAction("AimPosition", throwIfNotFound: true);
        m_AimingActions_SpinPosition = m_AimingActions.FindAction("SpinPosition", throwIfNotFound: true);
        m_AimingActions_ResetSpin = m_AimingActions.FindAction("ResetSpin", throwIfNotFound: true);
        m_AimingActions_ChangeClub = m_AimingActions.FindAction("ChangeClub", throwIfNotFound: true);
        m_AimingActions_ZoomOut = m_AimingActions.FindAction("ZoomOut", throwIfNotFound: true);
        m_AimingActions_ZoomOutAim = m_AimingActions.FindAction("ZoomOutAim", throwIfNotFound: true);
        m_AimingActions_ShortPutt = m_AimingActions.FindAction("ShortPutt", throwIfNotFound: true);
        m_AimingActions_SubmitAim = m_AimingActions.FindAction("SubmitAim", throwIfNotFound: true);
        // HittingActions
        m_HittingActions = asset.FindActionMap("HittingActions", throwIfNotFound: true);
        m_HittingActions_CancelHit = m_HittingActions.FindAction("CancelHit", throwIfNotFound: true);
        m_HittingActions_StartHit = m_HittingActions.FindAction("StartHit", throwIfNotFound: true);
        m_HittingActions_SubmitHit = m_HittingActions.FindAction("SubmitHit", throwIfNotFound: true);
        // PowerUps
        m_PowerUps = asset.FindActionMap("PowerUps", throwIfNotFound: true);
        m_PowerUps_UsePowerUp = m_PowerUps.FindAction("UsePowerUp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_TrackedDevicePosition;
    private readonly InputAction m_UI_TrackedDeviceOrientation;
    public struct UIActions
    {
        private @GolfControls m_Wrapper;
        public UIActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // PromptPlayer
    private readonly InputActionMap m_PromptPlayer;
    private IPromptPlayerActions m_PromptPlayerActionsCallbackInterface;
    private readonly InputAction m_PromptPlayer_Continue;
    private readonly InputAction m_PromptPlayer_Skip;
    public struct PromptPlayerActions
    {
        private @GolfControls m_Wrapper;
        public PromptPlayerActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_PromptPlayer_Continue;
        public InputAction @Skip => m_Wrapper.m_PromptPlayer_Skip;
        public InputActionMap Get() { return m_Wrapper.m_PromptPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PromptPlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPromptPlayerActions instance)
        {
            if (m_Wrapper.m_PromptPlayerActionsCallbackInterface != null)
            {
                @Continue.started -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnContinue;
                @Continue.performed -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnContinue;
                @Continue.canceled -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnContinue;
                @Skip.started -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnSkip;
                @Skip.performed -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnSkip;
                @Skip.canceled -= m_Wrapper.m_PromptPlayerActionsCallbackInterface.OnSkip;
            }
            m_Wrapper.m_PromptPlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Continue.started += instance.OnContinue;
                @Continue.performed += instance.OnContinue;
                @Continue.canceled += instance.OnContinue;
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
            }
        }
    }
    public PromptPlayerActions @PromptPlayer => new PromptPlayerActions(this);

    // AimingActions
    private readonly InputActionMap m_AimingActions;
    private IAimingActionsActions m_AimingActionsActionsCallbackInterface;
    private readonly InputAction m_AimingActions_AimPosition;
    private readonly InputAction m_AimingActions_SpinPosition;
    private readonly InputAction m_AimingActions_ResetSpin;
    private readonly InputAction m_AimingActions_ChangeClub;
    private readonly InputAction m_AimingActions_ZoomOut;
    private readonly InputAction m_AimingActions_ZoomOutAim;
    private readonly InputAction m_AimingActions_ShortPutt;
    private readonly InputAction m_AimingActions_SubmitAim;
    public struct AimingActionsActions
    {
        private @GolfControls m_Wrapper;
        public AimingActionsActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @AimPosition => m_Wrapper.m_AimingActions_AimPosition;
        public InputAction @SpinPosition => m_Wrapper.m_AimingActions_SpinPosition;
        public InputAction @ResetSpin => m_Wrapper.m_AimingActions_ResetSpin;
        public InputAction @ChangeClub => m_Wrapper.m_AimingActions_ChangeClub;
        public InputAction @ZoomOut => m_Wrapper.m_AimingActions_ZoomOut;
        public InputAction @ZoomOutAim => m_Wrapper.m_AimingActions_ZoomOutAim;
        public InputAction @ShortPutt => m_Wrapper.m_AimingActions_ShortPutt;
        public InputAction @SubmitAim => m_Wrapper.m_AimingActions_SubmitAim;
        public InputActionMap Get() { return m_Wrapper.m_AimingActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AimingActionsActions set) { return set.Get(); }
        public void SetCallbacks(IAimingActionsActions instance)
        {
            if (m_Wrapper.m_AimingActionsActionsCallbackInterface != null)
            {
                @AimPosition.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnAimPosition;
                @AimPosition.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnAimPosition;
                @AimPosition.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnAimPosition;
                @SpinPosition.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSpinPosition;
                @SpinPosition.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSpinPosition;
                @SpinPosition.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSpinPosition;
                @ResetSpin.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnResetSpin;
                @ResetSpin.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnResetSpin;
                @ResetSpin.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnResetSpin;
                @ChangeClub.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnChangeClub;
                @ChangeClub.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnChangeClub;
                @ChangeClub.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnChangeClub;
                @ZoomOut.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOut;
                @ZoomOut.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOut;
                @ZoomOut.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOut;
                @ZoomOutAim.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOutAim;
                @ZoomOutAim.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOutAim;
                @ZoomOutAim.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnZoomOutAim;
                @ShortPutt.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnShortPutt;
                @ShortPutt.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnShortPutt;
                @ShortPutt.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnShortPutt;
                @SubmitAim.started -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSubmitAim;
                @SubmitAim.performed -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSubmitAim;
                @SubmitAim.canceled -= m_Wrapper.m_AimingActionsActionsCallbackInterface.OnSubmitAim;
            }
            m_Wrapper.m_AimingActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AimPosition.started += instance.OnAimPosition;
                @AimPosition.performed += instance.OnAimPosition;
                @AimPosition.canceled += instance.OnAimPosition;
                @SpinPosition.started += instance.OnSpinPosition;
                @SpinPosition.performed += instance.OnSpinPosition;
                @SpinPosition.canceled += instance.OnSpinPosition;
                @ResetSpin.started += instance.OnResetSpin;
                @ResetSpin.performed += instance.OnResetSpin;
                @ResetSpin.canceled += instance.OnResetSpin;
                @ChangeClub.started += instance.OnChangeClub;
                @ChangeClub.performed += instance.OnChangeClub;
                @ChangeClub.canceled += instance.OnChangeClub;
                @ZoomOut.started += instance.OnZoomOut;
                @ZoomOut.performed += instance.OnZoomOut;
                @ZoomOut.canceled += instance.OnZoomOut;
                @ZoomOutAim.started += instance.OnZoomOutAim;
                @ZoomOutAim.performed += instance.OnZoomOutAim;
                @ZoomOutAim.canceled += instance.OnZoomOutAim;
                @ShortPutt.started += instance.OnShortPutt;
                @ShortPutt.performed += instance.OnShortPutt;
                @ShortPutt.canceled += instance.OnShortPutt;
                @SubmitAim.started += instance.OnSubmitAim;
                @SubmitAim.performed += instance.OnSubmitAim;
                @SubmitAim.canceled += instance.OnSubmitAim;
            }
        }
    }
    public AimingActionsActions @AimingActions => new AimingActionsActions(this);

    // HittingActions
    private readonly InputActionMap m_HittingActions;
    private IHittingActionsActions m_HittingActionsActionsCallbackInterface;
    private readonly InputAction m_HittingActions_CancelHit;
    private readonly InputAction m_HittingActions_StartHit;
    private readonly InputAction m_HittingActions_SubmitHit;
    public struct HittingActionsActions
    {
        private @GolfControls m_Wrapper;
        public HittingActionsActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CancelHit => m_Wrapper.m_HittingActions_CancelHit;
        public InputAction @StartHit => m_Wrapper.m_HittingActions_StartHit;
        public InputAction @SubmitHit => m_Wrapper.m_HittingActions_SubmitHit;
        public InputActionMap Get() { return m_Wrapper.m_HittingActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HittingActionsActions set) { return set.Get(); }
        public void SetCallbacks(IHittingActionsActions instance)
        {
            if (m_Wrapper.m_HittingActionsActionsCallbackInterface != null)
            {
                @CancelHit.started -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnCancelHit;
                @CancelHit.performed -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnCancelHit;
                @CancelHit.canceled -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnCancelHit;
                @StartHit.started -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnStartHit;
                @StartHit.performed -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnStartHit;
                @StartHit.canceled -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnStartHit;
                @SubmitHit.started -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnSubmitHit;
                @SubmitHit.performed -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnSubmitHit;
                @SubmitHit.canceled -= m_Wrapper.m_HittingActionsActionsCallbackInterface.OnSubmitHit;
            }
            m_Wrapper.m_HittingActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CancelHit.started += instance.OnCancelHit;
                @CancelHit.performed += instance.OnCancelHit;
                @CancelHit.canceled += instance.OnCancelHit;
                @StartHit.started += instance.OnStartHit;
                @StartHit.performed += instance.OnStartHit;
                @StartHit.canceled += instance.OnStartHit;
                @SubmitHit.started += instance.OnSubmitHit;
                @SubmitHit.performed += instance.OnSubmitHit;
                @SubmitHit.canceled += instance.OnSubmitHit;
            }
        }
    }
    public HittingActionsActions @HittingActions => new HittingActionsActions(this);

    // PowerUps
    private readonly InputActionMap m_PowerUps;
    private IPowerUpsActions m_PowerUpsActionsCallbackInterface;
    private readonly InputAction m_PowerUps_UsePowerUp;
    public struct PowerUpsActions
    {
        private @GolfControls m_Wrapper;
        public PowerUpsActions(@GolfControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UsePowerUp => m_Wrapper.m_PowerUps_UsePowerUp;
        public InputActionMap Get() { return m_Wrapper.m_PowerUps; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PowerUpsActions set) { return set.Get(); }
        public void SetCallbacks(IPowerUpsActions instance)
        {
            if (m_Wrapper.m_PowerUpsActionsCallbackInterface != null)
            {
                @UsePowerUp.started -= m_Wrapper.m_PowerUpsActionsCallbackInterface.OnUsePowerUp;
                @UsePowerUp.performed -= m_Wrapper.m_PowerUpsActionsCallbackInterface.OnUsePowerUp;
                @UsePowerUp.canceled -= m_Wrapper.m_PowerUpsActionsCallbackInterface.OnUsePowerUp;
            }
            m_Wrapper.m_PowerUpsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UsePowerUp.started += instance.OnUsePowerUp;
                @UsePowerUp.performed += instance.OnUsePowerUp;
                @UsePowerUp.canceled += instance.OnUsePowerUp;
            }
        }
    }
    public PowerUpsActions @PowerUps => new PowerUpsActions(this);
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
    }
    public interface IPromptPlayerActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
    }
    public interface IAimingActionsActions
    {
        void OnAimPosition(InputAction.CallbackContext context);
        void OnSpinPosition(InputAction.CallbackContext context);
        void OnResetSpin(InputAction.CallbackContext context);
        void OnChangeClub(InputAction.CallbackContext context);
        void OnZoomOut(InputAction.CallbackContext context);
        void OnZoomOutAim(InputAction.CallbackContext context);
        void OnShortPutt(InputAction.CallbackContext context);
        void OnSubmitAim(InputAction.CallbackContext context);
    }
    public interface IHittingActionsActions
    {
        void OnCancelHit(InputAction.CallbackContext context);
        void OnStartHit(InputAction.CallbackContext context);
        void OnSubmitHit(InputAction.CallbackContext context);
    }
    public interface IPowerUpsActions
    {
        void OnUsePowerUp(InputAction.CallbackContext context);
    }
}
